version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "postgres:db"
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "8080"
    ports:
      - "8080:8080"
volumes:
  data: